name: OpenAI Twitter Bot
on:
  schedule:
    # Run at 10:00 UTC on Monday, Wednesday, and Friday
    - cron: '0 10 * * 1,3,5'
  # Allow manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  post-tweet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate and post tweet
      run: |
        python openai_twitter.py
        
    - name: Commit post history
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "Github Actions"
        git add post_history.json
        git commit -m "Update post history" || echo "No changes to commit"
        git push origin main || echo "No changes to push"
      
    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}